// src/renderer/components/LandingPage/BlockEditor.vue

<template>
  <div class="collection-editor-wrapper">
    <div class="title">TODO: Block</div>
  </div>
</template>

<script>
  export default {
    props: {
      definition: {},
      collection: {}
    }
  }
</script>

<style scoped>
  .collection-editor-wrapper {
    padding: 20px;
  }

  .title {
    font-size: 24px;
    margin-bottom: 10px;
  }

  label {
    margin-right: 20px;
  }
</style>

// src/renderer/components/BlockEditor.svelte
<script>
  import DataEditor from "./DataEditor";

  export let block = null;
  export let definition = null;
  export let data = null;

  function handleChange() {}
</script>

<style>
  .title {
    font-size: 24px;
    margin-bottom: 10px;
  }
</style>

<div class="block-editor-wrapper">
  <div class="title">Block: {block.name}</div>
  <DataEditor {definition} {data} on:change={handleChange} />
</div>
