// src/renderer/components/Help/HelpSection.vue

<template>
  <div class="help-container">
    <settings-help v-if="section === 'Settings'"/>
    <data-help v-if="section === 'Data'"/>
    <pages-help v-if="section === 'Pages'"/>
    <blocks-help v-if="section === 'Blocks'"/>
  </div>
</template>

<script>
  import SettingsHelp from './SettingsHelp'
  import DataHelp from './DataHelp'
  import PagesHelp from './PagesHelp'
  import BlocksHelp from './BlocksHelp'

  export default {
    components: { SettingsHelp, DataHelp, PagesHelp, BlocksHelp },
    props: {
      section: ''
    }
  }
</script>

<style scoped>
  .help-container {
    padding: 20px;
  }
</style>

// src/renderer/help/HelpSection.svelte
<script>
  import SettingsHelp from "./SettingsHelp";
  import DataHelp from "./DataHelp";
  import PagesHelp from "./PagesHelp";
  import BlocksHelp from "./BlocksHelp";

  export let section = "";
</script>

<style>
  .help-container {
    padding: 20px;
  }
</style>

<template>
  <div class="help-container">
    {#if section === 'Settings'}
      <SettingsHelp />
    {:else if section === 'Data'}
      <DataHelp />
    {:else if section === 'Pages'}
      <PagesHelp />
    {:else if section === 'Blocks'}
      <BlocksHelp />
    {/if}
  </div>
</template>
