// src/renderer/components/Help/PagesHelp.vue

<template>
  <div class="help-wrapper">
    <div class="title">Pages</div>
    <p>
      These are the templates for each page in your site.
    </p>
    <p>
      Pages can be either layout pages (which are used as a template for other pages) or pages that contain your data.
    </p>
  </div>
</template>

<script>
  export default {
  }
</script>

<style scoped>
  .title {
    font-size: 24px;
    margin-bottom: 10px;
  }
</style>

// src/renderer/help/PagesHelp.svelte
<style>
  .title {
    font-size: 24px;
    margin-bottom: 10px;
  }
</style>

<template>
  <div class="help-wrapper">
    <div class="title">Pages</div>
    <p>These are the templates for each page in your site.</p>
    <p>
      Pages can be either layout pages (which are used as a template for other
      pages) or pages that contain your data.
    </p>
  </div>
</template>
