// src/renderer/help/DataHelp.svelte
<style>
  .title {
    font-size: 24px;
    margin-bottom: 10px;
  }
</style>

<template>
  <div class="help-wrapper">
    <div class="title">Data</div>
    <p>
      Data is used to build your pages. For example, you may have a list on a
      page showing all of your products and then a detail page for each product.
      The list page and the detail pages would be built from the same source of
      data, which would be created in this section.
    </p>
  </div>
</template>

// src/renderer/components/Help/DataHelp.vue

<template>
  <div class="help-wrapper">
    <div class="title">Data</div>
    <p>
      Data is used to build your pages. For example, you may have a list on a page showing all of your
      products and then a detail page for each product. The list page and the detail pages would be
      built from the same source of data, which would be created in this section.
    </p>
  </div>
</template>

<script>
  export default {
  }
</script>

<style scoped>
  .title {
    font-size: 24px;
    margin-bottom: 10px;
  }
</style>
