// src/renderer/help/SettingsHelp.svelte
<style>
  .title {
    font-size: 24px;
    margin-bottom: 10px;
  }
</style>

<template>
  <div class="help-wrapper">
    <div class="title">Settings</div>
    <p>
      Settings affect the whole of your site, whether it be the icon and title
      shown at the top of the browser, the description text that search engines
      will use to find your site, or the fonts and colors used to display your
      pages.
    </p>
    <p>Settings can often be overridden by settings on a page.</p>
  </div>
</template>

// src/renderer/components/Help/SettingsHelp.vue

<template>
  <div class="help-wrapper">
    <div class="title">Settings</div>
    <p>
      Settings affect the whole of your site, whether it be the icon and title shown at the top of the
      browser, the description text that search engines will use to find your site, or the fonts and
      colors used to display your pages.
    </p>
    <p>
      Settings can often be overridden by settings on a page.
    </p>
  </div>
</template>

<script>
  export default {
  }
</script>

<style scoped>
  .title {
    font-size: 24px;
    margin-bottom: 10px;
  }
</style>
