// src/renderer/components/DataEditor.svelte
<script>
  import { beforeUpdate } from "svelte";

  export let definition = null;
  export let data = null;

  beforeUpdate(() => {
    // Update data from the definition, just in case it hasn't been loaded or the template has changed
    definition.definitions.forEach(def => {
      if (!data[def.key]) {
        // TODO: Depends on the type, I guess...
        data[def.key] = "";
      }
    });
  });
</script>

<style>
  label {
    margin-right: 20px;
  }
</style>

<div class="data-editor-wrapper">
  <table>
    <tbody>
      {#each definition.definitions as def, index}
        <tr>
          <td>
            <label for={def.key}>{def.name}</label>
          </td>
          <td>
            <input type="text" id={def.key} bind:value={data[def.key]} />
          </td>
        </tr>
      {/each}
    </tbody>
  </table>
</div>

// src/renderer/components/Components/DataEditor.vue
<template>
  <div class="data-editor-wrapper">
    <table>
      <tbody>
        <tr v-for="(def, index) in definition.definitions" :key="index">
          <td>
            <label :for="def.key">{{ def.name }}</label>
          </td>
          <td>
            <input type="text" :id="def.key" :value="data[def.key]" @input="$emit('change', def.key, $event.target.value)">
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

<script>
  export default {
    props: {
      definition: {},
      data: {},
      file: ''
    }
  }
</script>

<style lang="scss" scoped>
  label {
    margin-right: 20px;
  }
</style>
