// src/renderer/components/DefinitionsEditor.svelte
<script>
  export let definitions = [];
  export let collection = [];

  import Icon from "./Icon";
  import { faPlus } from "@fortawesome/free-solid-svg-icons/faPlus";

  function addDefinition() {
    definitions.push({
      key: "",
      name: "",
      type: "text"
    });
    // HACK: Force reactivity
    definitions = definitions;
  }

  function setKey(e, definition) {
    const oldKey = definition.key;
    const newKey = e.target.value;
    definition.key = newKey;
    // Update items in the collection with this new key
    collection.forEach(item => {
      item[newKey] = item[oldKey];
      item[oldKey] = undefined;
    });
  }
</script>

<style lang="scss">
  .edit-definition-buttons {
    button {
      background-color: #ddd;
      border: 1px solid transparent;
      border-radius: 2px;
      color: inherit;
      padding: 10px;
      width: 100%;
    }
    button:hover {
      background-color: darken(#ddd, 9%);
    }
    button:focus {
      border: 1px solid rgba(0, 0, 0, 0.15);
    }
  }
</style>

<div class="definitions-editor-wrapper">
  <table>
    <thead>
      <tr>
        <td>Key</td>
        <td>Name</td>
        <td>Type</td>
      </tr>
    </thead>
    <tbody>
      {#each definitions as def, index}
        <tr>
          <td>
            <input type="text" value={def.key} on:input={e => setKey(e, def)} />
          </td>
          <td>
            <input type="text" bind:value={def.name} />
          </td>
          <td>
            <input type="text" bind:value={def.type} />
          </td>
        </tr>
      {/each}
    </tbody>
  </table>
  <div class="edit-definition-buttons">
    <button title="Add a definition" on:click={addDefinition}>
      <Icon icon={faPlus} />
    </button>
  </div>
</div>

// src/renderer/components/Components/DefinitionsEditor.vue
<template>
  <div class="definiot-editor-wrapper">
    <table>
      <thead>
        <tr>
          <td>Key</td>
          <td>Name</td>
          <td>Type</td>
        </tr>
      </thead>
      <tbody>
        <tr v-for="(def, index) in definitions" :key="index">
          <td>
            <input type="text" :value="def.key" @input="setDefinitionValue(def, 'key', $event.target.value)">
          </td>
          <td>
            <input type="text" :value="def.name" @input="setDefinitionValue(def, 'name', $event.target.value)">
          </td>
          <td>
            <input type="text" :value="def.type" @input="setDefinitionValue(def, 'type', $event.target.value)">
          </td>
        </tr>
      </tbody>
    </table>
    <div class="edit-definition-buttons">
      <button title="Add a definition" @click="addDefinition">
        <fa icon="plus"/>
      </button>
    </div>
  </div>
</template>

<script>
  import { mapMutations } from 'vuex'

  export default {
    props: {
      definitions: Array,
      collection: Array
    },
    methods: {
      ...mapMutations([
        'ADD_DEFINITION',
        'SET_DEFINITION_FIELDS'
      ]),
      addDefinition () {
        this.ADD_DEFINITION(this.definitions)
      },
      setDefinitionValue (definition, field, value) {
        const fields = {}
        fields[field] = value
        this.SET_DEFINITION_FIELDS({ definition, fields, collection: this.collection })
      }
    }
  }
</script>

<style lang="scss" scoped>
  .title {
    font-size: 24px;
    margin-bottom: 10px;
  }

  label {
    margin-right: 20px;
  }

  .edit-definition-buttons {
    button {
      background-color: #ddd;
      border: 1px solid transparent;
      border-radius: 2px;
      color: inherit;
      padding: 10px;
      width: 100%;
    }
    button:hover {
      background-color: darken(#ddd, 9%);
    }
    button:focus {
      border: 1px solid rgba(0, 0, 0, 0.15);
    }
  }
</style>
